package testdata

// This file contains test helper functions and data for apilog E2E tests
// Generated by test-param-generator tool

// TestParams represents the structure of test parameters for apilog API
type TestParams struct {
	GetLogs GetLogsParams `json:"GetLogs"`
	GetLog  GetLogParams  `json:"GetLog"`
}

// GetLogsParams represents query parameters for GetLogs method
type GetLogsParams struct {
	QueryParams struct {
		CreatedDate string `json:"created_date"`
		CreatedAt   string `json:"created_at"`
		Cursor      string `json:"cursor"`
	} `json:"queryParams"`
}

// GetLogParams represents path parameters for GetLog method
type GetLogParams struct {
	PathParams struct {
		ApiLogID string `json:"api_log_id"`
	} `json:"pathParams"`
}
