info:
  contact:
    name: Anti-Pattern
  description: Schema
  title: SaaSus Auth API Schema
  version: 1.0.0
  x-description-i18n:
    jpn: スキーマ
openapi: 3.0.0
paths:
  /credentials:
    get:
      description: |
        Get ID token, access token, and refresh token using a temporary code or a refresh token.
      operationId: GetAuthCredentials
      parameters:
      - description: Temp Code
        in: query
        name: code
        schema:
          example: 69e732d6-8ecc-45c4-c2eb-8438f7ffe775
          type: string
        x-description-i18n:
          jpn: 一時コード
      - description: |
          Authentication Flow
          tempCodeAuth: Getting authentication information using a temporary code
          refreshTokenAuth: Getting authentication information using a refresh token
          If not specified, it will be tempCodeAuth
        in: query
        name: auth-flow
        schema:
          enum:
          - tempCodeAuth
          - refreshTokenAuth
          type: string
        x-description-i18n:
          jpn: |
            認証フロー
            tempCodeAuth: 一時コードを利用した認証情報の取得
            refreshTokenAuth: リフレッシュトークンを利用した認証情報の取得
            指定されていない場合は tempCodeAuth になります
      - description: Refresh Token
        in: query
        name: refresh-token
        schema:
          type: string
        x-description-i18n:
          jpn: リフレッシュトークン
      responses:
        "200":
          content:
            application/json:
              schema:
                properties:
                  access_token:
                    description: Access token
                    title: Access Token
                    type: string
                    x-description-i18n:
                      jpn: アクセストークン
                    x-title-i18n:
                      jpn: アクセストークン
                  id_token:
                    description: ID token
                    title: ID Token
                    type: string
                    x-description-i18n:
                      jpn: IDトークン
                    x-title-i18n:
                      jpn: IDトークン
                  refresh_token:
                    description: Refresh token
                    title: Refresh Token
                    type: string
                    x-description-i18n:
                      jpn: リフレッシュトークン
                    x-title-i18n:
                      jpn: リフレッシュトークン
                required:
                - id_token
                - access_token
                title: Authentication/Authorization Information
                type: object
                x-title-i18n:
                  jpn: 認証・認可情報
          description: OK
        "404":
          content:
            application/json:
              schema:
                properties:
                  data:
                    additionalProperties: true
                    example:
                      sign_in_page_url: auth.dev.saasus.io
                    type: object
                  message:
                    description: Error message
                    type: string
                  type:
                    description: permission_denied
                    type: string
                required:
                - type
                - message
          description: Not Found
        "500":
          content:
            application/json:
              schema:
                properties:
                  data:
                    additionalProperties: true
                    example:
                      sign_in_page_url: auth.dev.saasus.io
                    type: object
                  message:
                    description: Error message
                    type: string
                  type:
                    description: permission_denied
                    type: string
                required:
                - type
                - message
          description: Internal Server Error
      summary: Get Authentication/Authorization Information
      tags:
      - credential
      x-description-i18n:
        jpn: |
          一時コードまたはリフレッシュトークンを利用してIDトークン・アクセストークン・リフレッシュトークンを取得する。
      x-summary-i18n:
        jpn: 認証・認可情報の取得
    post:
      description: |
        Temporarily save the parameter for the ID token, access token, and refresh token and return a temporary code for obtaining.
        Temporary codes are valid for 10 seconds from issuance.
      operationId: CreateAuthCredentials
      requestBody:
        content:
          application/json:
            schema:
              properties:
                access_token:
                  description: Access token
                  title: Access Token
                  type: string
                  x-description-i18n:
                    jpn: アクセストークン
                  x-title-i18n:
                    jpn: アクセストークン
                id_token:
                  description: ID token
                  title: ID Token
                  type: string
                  x-description-i18n:
                    jpn: IDトークン
                  x-title-i18n:
                    jpn: IDトークン
                refresh_token:
                  description: Refresh token
                  title: Refresh Token
                  type: string
                  x-description-i18n:
                    jpn: リフレッシュトークン
                  x-title-i18n:
                    jpn: リフレッシュトークン
              required:
              - id_token
              - access_token
              title: Authentication/Authorization Information
              type: object
              x-title-i18n:
                jpn: 認証・認可情報
      responses:
        "201":
          content:
            application/json:
              schema:
                properties:
                  code:
                    example: 69e732d6-8ecc-45c4-c2eb-8438f7ffe775
                    type: string
                required:
                - code
                type: object
          description: Created
        "400":
          content:
            application/json:
              schema:
                properties:
                  data:
                    additionalProperties: true
                    example:
                      sign_in_page_url: auth.dev.saasus.io
                    type: object
                  message:
                    description: Error message
                    type: string
                  type:
                    description: permission_denied
                    type: string
                required:
                - type
                - message
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                properties:
                  data:
                    additionalProperties: true
                    example:
                      sign_in_page_url: auth.dev.saasus.io
                    type: object
                  message:
                    description: Error message
                    type: string
                  type:
                    description: permission_denied
                    type: string
                required:
                - type
                - message
          description: Unauthorized
        "500":
          content:
            application/json:
              schema:
                properties:
                  data:
                    additionalProperties: true
                    example:
                      sign_in_page_url: auth.dev.saasus.io
                    type: object
                  message:
                    description: Error message
                    type: string
                  type:
                    description: permission_denied
                    type: string
                required:
                - type
                - message
          description: Internal Server Error
      summary: Save Authentication/Authorization Information
      tags:
      - credential
      x-description-i18n:
        jpn: |
          引数のIDトークン・アクセストークン・リフレッシュトークンを一時保存し取得用の一時コードを返却する。
          一時コードの有効期間は発行から10秒です。
      x-summary-i18n:
        jpn: 認証・認可情報の保存
security:
- Bearer: []
servers:
- description: Production API Server
  url: https://api.saasus.io/v1/auth
tags:
- description: Authentication/Authorization Info
  name: credential
  x-description-i18n:
    jpn: 認証・認可情報
